# Site settings
title:          lsm
description:    "기술 기록 및 회고 블로그"
baseurl:        "/"
url:            "https://songmilee.github.io"

# Author
author:
  name:         lsm
  email:        lsm941010@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate


# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# disqus comment
disqus_url : "https://songmilee.disqus.com"
disqus_id : "songmilee"
